### ISSUE TITLE
DKPro 1.9.0-SNAPSHOT cannot be built under Windows due to AUX POS type (reserved file name)

### ISSUE THREAD

**Issue by ferschke** [dkpro/dkpro-core#984] opened 2016-11-14 19:29 UTC
The POS type AUX0 (DKPro 1.8.0 and earlier) was renamed to AUX (de.tudarmstadt.ukp.dkpro.core.api.lexmorph.type.pos.AUX) in the current 1.9.0-SNAPSHOT.
This prevents DKPro to build under windows because AUX is a reserved name. [1]

(Try to create a file named AUX or AUX.txt on a Windows system - you'll get the error that "The specified device name is invalid"

Suggested fix: rename the type to AUX0 again

[1] https://blog.onetechnical.com/2006/11/16/forbidden-file-and-folder-names-on-windows/

**Comment by reckart** [comment] 2016-11-14 21:25
Duplicate of #414.

**Closed by reckart** 2016-11-14 21:25 UTC
