### ISSUE TITLE
Adding the RF-Tagger

### ISSUE THREAD

**Issue by Horsmann** [dkpro/dkpro-core#684] opened 2015-10-30 14:31 UTC
Hi,
there is the RF-Tagger which is not yet in DKPro Core :)
See: http://www.cis.uni-muenchen.de/~schmid/tools/RFTagger/

It is a Helmut Schmid tagger which seems not as restrictive as the Treetagger
"This package contains the RFTagger which is freely available for academic research and education."

The tagger supports the language German, Czech, Slovene, Slovak, Hungarian, and Russian

This tagger uses at least for German the very complex German Tiger Treebank tagset: See an output example below.

Are there any objections if I add this tagger?

```
Das	PRO.Dem.Subst.-.Nom.Sg.Neut
ist	VFIN.Sein.3.Sg.Pres.Ind
ein	ART.Indef.Nom.Sg.Masc
Testsatz	N.Reg.Nom.Sg.Masc
.	SYM.Pun.Sent

Das	PRO.Dem.Subst.-.Nom.Sg.Neut
ist	VFIN.Sein.3.Sg.Pres.Ind
noch	ADV
ein	ART.Indef.Nom.Sg.Masc
Satz	N.Reg.Nom.Sg.Masc
.	SYM.Pun.Sent
```

* [x] switch model packaging from dir-based to file-based (?)
* [x] package all models in rftagger package (not only the German one)
* [x] upload models to UKP OSS repository
* [x] add models to model overview for DKPro Core 1.8.0
* [x] add models to model overview for DKPro Core 1.9.0
* [x] remove reference to LT repositories from POM
* [x] mention components in asciidoc

**Comment by zesch** [comment] 2015-10-30 14:56
I don't think there will be objections :)

**Comment by Horsmann** [comment] 2015-10-30 17:42
What are the naming rules for the Variant parameter?
The corpora used are rather long names
German: Tiger2 treebank
Czech:  Czech Academic Corpus 1.0

Variant="tiger" or "tiger2treebank" ?

**Comment by judithek** [comment] 2015-10-30 19:07
thanks Tobias! very nice enhancement!

**Comment by reckart** [comment] 2015-10-30 20:30
I usually look what name the upstream model has. So if the upstream model name were like "model-tiger.bin", I'd use "tiger" and if it were "model-tiger2treebank.bin" I'd use "tiger2treebank". The idea is that the user can relate the DKPro Core variant to the upstream model.

**Comment by Horsmann** [comment] 2015-10-30 22:38
Ok thanks :)

@reckart  I tried to link the binary statically on OS-X, but this does not seem to work. If I compile it with static linking the compiler complains that `library not found for -lcrt0.o`. 
What I read so far is that the issue lies in OSX not providing static linking of the C runtime. In the case of OsX this should not matter and I can use the dynamically linked binaries, right? The OSX versions should be all the same with respect to the by default pre-installed dynamic C libraries ?!

**Comment by reckart** [comment] 2015-10-31 09:35
*static linking on OS X:* it is not possible to statically link crt0 - but all other libraries can typically be linked statically. If rftagger has no additional library dependencies, then this is a non-issue. I think you can check this by doing a regular dynamic compile and then examine the binary using "otool -L"

*streaming:* there are two prerequisites: 1) the tool must accept input on stdin and provide output on stdout. 2) there must be some way to indicate the end of a document to the tool on stdin without terminating the tool. TT4J does this simply by sending a language-dependent sequence of tokens after the document on stdin and when it starts seeing this sequence on stdout, it knows that all document data has been written to stdout. In most cases it works to send ". . . . . ." for TreeTagger - for some reason the French model doesn't like it and requires an actual sentence. Helmut Schmid has at some point I think enhanced TreeTagger to flush its state to the output after sending several empty lines or something like that - but it doesn't work in all cases.

I don't know how rftagger behaves. Try it, check the sources, or ask Helmut Schmid ;)

**Comment by reckart** [comment] 2015-10-31 09:36
Anyway - cool thing integrating the rftagger :+1:

**Comment by Horsmann** [comment] 2015-10-31 20:29
The RFtagger supports stdin/stdout. The input format is one-token-per-line this is not exactly the same as for the Treetagger which excepts full sentences?
I experimented a bit with the `ProcessBuilder` in Java, but seems it is not that easy to keep a process alive. I run into the issue that the process seem to die. Everytime I put data into in it clashes with an `stream closed` exception. This is essentially the same thing that these Treetagger do, no?

**Comment by reckart** [comment] 2015-10-31 22:45
If the process doesn't crash by itself, then it is usually not a problem to keep it alive. Make sure to use `        pb.redirectError(Redirect.INHERIT);` so you see any error messages produced by the process (cf. HunPosTagger in DKPro Core). 

TT4J does go a long way to clean up data before feeding it to TreeTagger etc. - but that would hopefully not be necessary for rftagger. Use the source, Luke ;)

**Comment by Horsmann** [comment] 2015-11-01 10:37
Ok thanks :)

How do I annotate the output? Do I simply put everything into the POS type?
The 2nd issue is that the pos-mapping files do not seem to support wildcards. I cannot map VFIN* to verb? So it seems to make sense to split the information up and just put VFIN als value into the Pos type, but where to store the remaining information?

Here an example output:
```
Wir		PRO.Pers.Subst.1.Nom.Pl.*
wohnen		VFIN.Full.1.Pl.Pres.Ind
seit		APPR.Dat
2		CARD
Jahren		N.Reg.Dat.Pl.Neut
in		APPR.In
dem		ART.Def.Dat.Sg.Neut
neuen		ADJA.Pos.Dat.Sg.Neut
Haus		N.Reg.Dat.Sg.Neut
´´´

**Comment by reckart** [comment] 2015-11-01 10:57
The non-POS information goes into the MorphologicalFeatures annotation which can be attached to a Token. See MorphologicalFeaturesParser e.g. used in SfstParser. The mappings used by the MorphologicalFeaturesParser do substring matching, e.g.:

```
#
# Feature: person
#
# Tagset: http://universaldependencies.github.io/docs/u/feat/Person.htmlhtml (2014-11-18)
#
person.1=<1[ps]>
person.2=<2[ps]>
person.3=<3[ps]>
```

This sets the `person` feature in the MorphologicalFeatures annotation to `1`, `2`, or `3` if the label produced by the tagger contains `<1p>` or `<2s>`, etc. Mind part after the equals sign is a regular expression in the mappings file so the square brackets, pipe symbols, etc. have special meaning.

To create a new mapping, copy the `/de/tudarmstadt/ukp/dkpro/core/api/lexmorph/tagset/TEMPLATE-morph.map` and add the mapping rules. The template also contains links to the documentation.

**Comment by Horsmann** [comment] 2015-11-01 19:01
Can someone interpret the verb annotation? What exactly is meant with "Full" ? I did not really find any documentation for the tagset so I am trial-and-erroring through the annotation. I cannot make sense of this one. 

Ich	O	PRO.Pers.Subst.1.Nom.Sg.*
laufe	O	VFIN.Full.1.Sg.Pres.Ind
,	O	SYM.Pun.Comma
ich	O	PRO.Pers.Subst.1.Nom.Sg.*
lief	O	VFIN.Full.1.Sg.Past.Ind
,	O	SYM.Pun.Comma
ich	O	PRO.Pers.Subst.1.Nom.Sg.*
bin	O	VFIN.Sein.1.Sg.Pres.Ind
gelaufen	O	VPP.Full.Psp
.	O	SYM.Pun.Sent

**Comment by zesch** [comment] 2015-11-01 19:09
My educated guess would be "Vollverb"

Maybe this is also helpful:
https://www.sketchengine.co.uk/rftagger-german/

**Comment by Horsmann** [comment] 2015-11-01 20:19
Ok thanks. I left the verb mappings in the morph-file unused. Rf prints sometimes "Full" and sometimes the lemma. I did not know what to make out of it. 

Could someone with Artifactory access upload the binaries and the models? The installation script with the file-urls lies in the script folder of the RFTagger.

**Comment by Horsmann** [comment] 2015-11-02 16:45
@zesch Could u upload the files to Artifactory?

**Comment by reckart** [comment] 2015-11-02 16:46
@betoboullosa is already at it.

**Comment by zesch** [comment] 2015-11-02 17:18
I didn't see @reckart's comment and uploaded the jars.

**Comment by reckart** [comment] 2015-11-02 17:27
@zesch looks like you did overwrite the ones beto had deployed already - no problem.

However, uploading the models is only half of the deal :) The model overview table on Google Drive also needs to be updated accordingly after models have been deployed. Again, @betoboullosa is working on that now. @zesch @Horsmann , I have shared the Google Drive folder with the model overviews with you for future updates.

**Comment by betoboullosa** [comment] 2015-11-02 17:45
Hi, I already updated the model table. @Horsmann 
<https://github.com/Horsmann>, if you have information regarding the POS 
columns to the other languages (Germany is ok), please update them.

BTW, I've noticed that in all the jars you used the "20151030.1" version 
number for all modules, except for 
de.tudarmstadt.ukp.dkpro.core.rftagger-bin, in which you put 
"20130430.0". Is that ok?

Best regards,
Beto

**Comment by Horsmann** [comment] 2015-11-02 18:59
Yes, the source code mentioned that date as last "edit". For the models I had no such info so I used the date when I downloaded the models.

**Comment by reckart** [comment] 2015-11-02 19:51
Why doesn't the build.xml download the models from their original locations? If you did not train them yourselves, the build.xml should contain the URLs for the original sources and also get the models from there.

To get the last changed date for any URL, you can use "curl -I", e.g. 

```
$ curl -I http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/data/german-par-linux-3.2-utf8.bin.gz
HTTP/1.1 200 OK
Date: Mon, 02 Nov 2015 19:51:02 GMT
Server: Apache/2.4.10 (Linux/SUSE)
Last-Modified: Fri, 07 Dec 2012 11:21:41 GMT
ETag: "759e5d-4d0416b731b40"
Accept-Ranges: bytes
Content-Length: 7708253
Content-Type: application/x-gzip
```

The `Last-Modified` is the one you are looking for.

**Comment by reckart** [comment] 2015-11-02 19:56
The model table on google drive should also be updated to point to the sites from where you got the models and name the  people/institutions that created them.

**Comment by Horsmann** [comment] 2015-11-03 09:36
I updated the model table. 

@reckart Is it such a big difference? The current way I am independent from changes to folder structure etc. that might apply in future changes. This seems more robust to me?

**Comment by reckart** [comment] 2015-11-03 17:37
@Horsmann for me it makes a huge difference. It is more transparent to us and to users of DKPro Core to see where the data comes from originally and we also know where to look for when we want to search for updated models. The only case where we put stuff on places such as bintray is when there absolutely is no upstream source, e.g. when the original authors do not offer precompiled binaries. Everything else should be obtained directly from upstream.

The independence for users comes from the models on zoidberg. I see no need to introduce a second upstream tier. The ant scripts are flexible enough to cope with any kind of upstream folder structure.

**Comment by Horsmann** [comment] 2015-11-04 09:49
@reckart I updated the build file. The `install-stub-and-upstream-folder ` has no md5 test like the `file` version. Is there any simple way of checking the md5 of the respective files? or the entire folder?

**Comment by reckart** [comment] 2015-11-04 10:08
Unfortunately not. Are the rftagger models consisting of more than one file?

**Comment by reckart** [comment] 2015-11-04 10:12
If you wish to add additional content to your model package (e.g license files etc.) which you don't need to md5-check, you can use `additionalUpstreamContent`:, e.g.

```
    		<additionalUpstreamContent>
    			<copy 
    				tofile="target/model-staging/META-INF/LICENSE.txt" 
    				file="target/download/smor/LICENSE"/>
    			<copy 
    				tofile="target/model-staging/META-INF/README.txt" 
    				file="target/download/smor/README"/>
    		</additionalUpstreamContent>
```

See for example in `de.tudarmstadt.ukp.dkpro.core.sfst-gpl/src/scripts/build.xml`.

**Comment by Horsmann** [comment] 2015-11-04 12:09
Yes, 2-3 files for each model atm. I would have wanted md5 for noticing changes to the model files i.e. which one did change. At the moment running the script might install the same files, but they might have been updated too.

**Comment by reckart** [comment] 2015-11-04 12:20
I would suggest to use the `install-stub-and-upstream-file` and use the md5 sum for the "par" file while not checking the lemma/abbreviation files and just keep them as `additionalUpstreamContent` at this time.

**Comment by reckart** [comment] 2015-11-04 12:31
I am also just noticing that the tagset metadata is missing from the models, e.g. 

```
<metadata>
  <entry key="model.encoding" value="UTF-8"/>
  <entry key="pos.tagset" value="stts"/>
  <entry key="morph.tagset" value="morphisto"/>
</metadata>
```

**Comment by Horsmann** [comment] 2015-11-04 12:33
I had until the last commit the binary and the models in the pom.xml. I removed them now since the models should not be by default in the pom of a tagger. Now the test crashes because it does not find the dependencies for the test-case I defined. How do I work around that?

**Comment by reckart** [comment] 2015-11-04 12:35
The binaries and models should be dependencies in the pom with the scope "test". Cf. the POM of any other annotator module. There is typically also a special configuration for the maven dependencies plugin in the poms to "ignore" these dependencies during pre-release checks - otherwise the checks will complain because they think the dependencies are unnecessary (no class files in there).

**Comment by Horsmann** [comment] 2015-11-04 12:55
Thx.

When I use the `install-stub-and-upstream-file` command I have to provide an extension parameter. If I set it I get this warning ` [copy] Warning: Could not find file /Users/toobee/Documents/Eclipse/dkpro-core/de.tudarmstadt.ukp.dkpro.core.rftagger-asl/target/download/german/param.par.props to copy.`

Furthermore, the file that is created in the upstream jar is named `tagger-de-tiger2treebank` it should be called `param.par`
What is happening o.0 ?

This is my new code block for German:
```
	<!-- GERMAN -->
		<mkdir dir="target/download/german" />

		<copy file="target/download/RFTagger/lib/german.par" tofile="target/download/german/param.par" />

		<install-stub-and-upstream-file 
			file="target/download/german/param.par" 
			groupId="de.tudarmstadt.ukp.dkpro.core"
			md5="365a63f36771637c4c97086661b7431e"
			artifactIdBase="de.tudarmstadt.ukp.dkpro.core.rftagger" 
			upstreamVersion="20150928" 
			metaDataVersion="1" 
			tool="tagger" 
			language="de" 
			variant="tiger2treebank"
			extension="">
			<additionalUpstreamContent>
				<copy tofile="target/download/german/german-rft-tagger-lemma-lexicon.txt" file="target/download/RFTagger/lib/german-rft-tagger-lemma-lexicon.txt" />
				<copy tofile="target/download/german/german-abbreviations" file="target/download/RFTagger/lib/german-abbreviations" />
			</additionalUpstreamContent>
			<metadata>
				<entry key="model.encoding" value="UTF-8" />
				<entry key="morph.tagset" value="tiger2treebank" />
				<entry key="morph.tagset" value="morphisto" />
			</metadata>
		</install-stub-and-upstream-file>
´´´

**Comment by reckart** [comment] 2015-11-04 13:00
> When I use the install-stub-and-upstream-file command I have to provide an extension parameter. If I set it I get this warning [copy] Warning: Could not find file /Users/toobee/Documents/Eclipse/dkpro-core/de.tudarmstadt.ukp.dkpro.core.rftagger-asl/target/download/german/param.par.props to copy.

You can ignore this warning. Actually, we should remove the special handling of props files now that there is support for additionalUpstreamContent. Would be another issue to raise against the resource-packager project.

The file should be called `tagger-de-tiger2treebank.<extension>` for install-stub-and-upstream-file. That is correct that way. But I see that you now have the problem that the way you extract and materialize the resources in the temporary location doesn't work anymore because it expects the structure created by install-stub-and-upstream-folder. So you can choose between not having md5 or changing your loading code. Thinking again about this, I would say my last suggestion to use `install-stub-and-upstream-file` is actually not the best way. Better stick with `install-stub-and-upstream-folder` and ignore the md5 for the time being (open the issue against resource-packager).

You cannot have two "morph.tagset" entries. I guess you do als POS tags, so you should have a "pos.tagset".

**Comment by Horsmann** [comment] 2015-11-04 13:18
I am really uncertain about the names of the tagsets of the other corpora. There do no seem to be that well known that they have a commonly known name. Shall I then only set the UTF-8 flag?

**Comment by reckart** [comment] 2015-11-04 13:31
The tagset name is used to choose the label-to-UIMA-type mapping. In cases were I did not find a good name, I had to invent one, otherwise I couldn't have named the mapping file.

**Comment by reckart** [comment] 2015-11-04 13:33
The "model.encoding" is not handled by DKPro Core by default. You have to implement special support for it in RfTagger (cf. SfstAnnotator).

**Comment by Horsmann** [comment] 2015-11-04 16:03
Ok, I made up really bad names and I am unsure about the morphological-parameter? Is Morphisto correct for all?

**Comment by reckart** [comment] 2015-11-04 16:11
No, morphisto is the name of a particular morphological resource for German (https://code.google.com/p/morphisto/). Maybe the tags from the German model you have conform to that, but likely not (you have to check). If not, you can check if there is any other mapping already in DKPro Core and if not, create a new one and find a suitable name for it. In the past, I have sometimes spend an hour to try tracking down publications on corpora, finding tagsets, and in particular also their documentations. If I found those, I often added them as comments to the build.xml file and also to the mapping file (sometimes only to the mappings file I guess).

Cf. `build.xml` file in mstparser module:

```
			<metadata>
				<entry key="DC.title" value="model.mte5.defnpout"/>
				<entry key="DC.creator" value="Željko Agić"/>
				<entry key="DC.identifier" value="http://nlp.ffzg.hr/data/depparsing/model.mte5.defnpout.tar.gz"/>
				<entry key="DC.rights" value="http://creativecommons.org/licenses/by-sa/3.0/"/>
				<!-- http://dx.doi.org/10.1007/978-3-642-40585-3_70 -->
	    		<entry key="pos.tagset" value="mte5-reduced"/>
				<!-- https://aclweb.org/anthology/W/W13/W13-4903.pdf -->
				<!-- setimes.hr has similar but not the same tags/guidelines as the Croatian Treebank-->
				<entry key="dependency.tagset" value="setimes.hr"/>
	    		<entry key="mstparser.param.order" value="2"/>
			</metadata>
```

E.g. the "mte5-reduced" here is made up by myself as they appeared to be using the mte5 (Multext East v5; http://nl.ijs.si/ME/V5/msd/html/) tagset, but only the top levels (kind of the first few characters).

**Comment by Horsmann** [comment] 2015-11-05 08:41
ok,

I copied over the code for loading the model information from SfstAnnotator. I am working with a directory and not with a file. 

So I attached my `param.par` file as suffix to the URL. I get an exception now that the file is not found in the jar.
The path that is used is incomplete. 
`JAR entry de/tudarmstadt/ukp/dkpro/core/rftagger/lib/tagger/de/param.par not found `
It should be /lib//tagger/de/`tiger2treebank`/param.par

If I add the information form the `variant` variable I get a bit further (variant is not necessarily set, isn't?)
I get `Caused by: java.io.IOException: Incompatible model. Must be a compact model.` 
What does compact model mean?

```
	    
			    URL fileUrl = new URL(aUrl,PARAMETER_FILE);
			    
			    try (LittleEndianDataInputStream is = new LittleEndianDataInputStream(
			            fileUrl.openStream())) {
                    byte type = is.readByte(); // "c" for "compact"
                    if (type != 0x63) {
                        throw new IOException("Incompatible model. Must be a compact model.");
                    }
                    byte enc = is.readByte(); // "0" for ??? - "1" for UTF-8
                    getLogger().info("Model encoding: " + (enc == 0 ? "unknown" : "UTF-8"));
                    short n = is.readShort(); // alphabet size
                    for (int i = 0; i < n; i++) {
                        @SuppressWarnings("unused")
                        int idx = is.readShort(); // need to read index
                        String symbol = readZeroTerminatedString(is, "UTF-8");
                        if (symbol.startsWith("<") && symbol.endsWith(">") && symbol.length() > 2) {
                            morphFeats.add(symbol);
                        }
                    }
                }
                addTagset(morphFeats);
```

**Comment by reckart** [comment] 2015-11-05 09:24
The loading code in SFST examines the SFST model and checks if the model is of a certain type. This code is absolutely specific to SFST models.

**Comment by betoboullosa** [comment] 2015-11-05 11:42
I just uploaded again the models and scheduled a new build in Jenkins. I also changed the rftagger's POM in order to directly use the staging area of zoidberg, until the issue is closed.

**Comment by betoboullosa** [comment] 2015-11-05 11:55
Just a clarification to @Horsmann: in our Artifactory, we have a "staging" area to temporariliy hold models and stuff until we are sure they don't break anything. Only then we move the artifacts to their proper final destination.

**Comment by Horsmann** [comment] 2015-11-05 14:31
@betoboullosa  thanks!

@reckart 
How do I load the pos.tagset information? I looked into TreeTagger and OpenNLP and for landing the pos-tags they all depend on some customised class that can ask the model for the number of its unique outcomes. I don't have this kind of information, what should I do with the pos.tagset parameter then?

I load the morphological tags like this, but it seems to be missing the same kind of information:
```
    @Override
            protected File produceResource(URL aUrl)
                throws IOException
            {
                Properties metadata = getResourceMetaData();
                SingletonTagset morphFeats = new SingletonTagset(MorphologicalFeatures.class,
                        metadata.getProperty("morph.tagset"));
                addTagset(morphFeats);
                
                

                File folder = ResourceUtils.getClasspathAsFolder(aUrl.toString(), true);
                return folder;
            }
```

**Comment by Horsmann** [comment] 2015-11-06 13:01
@betoboullosa Is the staging-artifactory publicly accessible ? 
This link runs into a dead end for me: http://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-staging-local

**Comment by Horsmann** [comment] 2015-11-10 10:15
@reckart 
What is missing atm is loading of the default model for a language. I looked into the OpenNLP tagger how it is done there. There is a file in the lib-folder which is loaded in the model provider. 

How is this file created? Or ask another way, why is it not automatically written by the ant-installation script? I also noticed that the Treetagger does not load the default model anymore, the line of code is commented.

**Comment by Horsmann** [comment] 2015-11-13 14:23
@reckart ping :)

**Comment by reckart** [comment] 2015-11-14 11:37
The default variants file needs to be created manually. It is not part of the model JARs, so it is not created by the build.xml. The file is for the component to know which model variant it should load depending on the language of the document.

I think we need another issue for the TreeTagger problem.

**Comment by Horsmann** [comment] 2015-12-04 14:35
@reckart Maybe you can help me?

I am having problems to track a bug in the RFTagger wrapper:

I use a Java-process call to let the binary run. I provide always one sentence to the binary and read/annotate the output.

After some time (a few thousand tagged sentences) I run into a blocking `reader.readLine()` call.
It stops always at the same sentence, but wenn I send in only this sentence or this sentence with a few sentences before/after this sentence the issue does not occur.
I don't think it is an issue with a particular sentence, but rather that the binary get problems at some point or the process that runs the binary.

All I can tell from the Java-site is that when I try to read the output the readLine() call blocks which means neither a "\n"-terminated newline was read nor "EOF". 

Currently, I read ~12000 sentences from my data set before this blocking-issue comes up. I also set the error-out to std-out, but there is no information either. Something just goes wrong and I can't locate the problem/cause.

Did you/someone had such a problem before?

**Comment by reckart** [comment] 2015-12-04 15:29
It could be that the rftagger process writes error messages to stderr and if you don't redirect stderr somewhere or read it, then at some point the stderr buffer will be full and the external process will hang waiting to be able to write additional messages.

If this is the problem, then the best way to solve it is to use `pb.redirectError(Redirect.INHERIT);` - I mentioned that already in another comment on this issue, but I see that you commented out the `redirectError` line in the source code of the annotator.

**Comment by Horsmann** [comment] 2015-12-08 15:00
Ok,
I have to admit I don't understand why this is necessary. I tried to read the error stream and flush it to remove the data that arrive there, but this does not seem to work. Only redirecting it the process that runs the tagger seems to work. 

If I add this line it works. The ugly side-effect is that the RfTagger spams for each sequence a number on the error-out. 
It is not such a big deal, but it is not pretty either.

**Comment by reckart** [comment] 2015-12-08 16:20
Check if RfTagger has maybe a command line option to make it operate quietly.

**Comment by Horsmann** [comment] 2015-12-13 11:19
@reckart 
I found the switch, thanks

I changed the installation script some time ago to only install the German model. If someone needs the other languages he or she can easily extend the script by looking at the German example and deal with defining those pos/morph mappings. 

The tagger runs now fast/stable. All that is left to do from my side is uploading the binary and the model anew into the DKPro artifactory. At the moment the pom.xml contains a repository-entry to our `LTL` artifactory. 
When this is done the issue can be closed?

**Comment by reckart** [comment] 2015-12-13 12:26
New models should be added to the model overview document on Google Drive for the respective DKPro Core version. I'll have a look at the module and respond if I find anything else.

**Comment by reckart** [comment] 2015-12-14 22:03
I had a rough look at the code and added several FIXMEs all over the place. These should all be resolved before closing the issue except for one: I think it might not be easily possible to restart the rftagger process if the language changes during processing (i.e. embed the RuntimeProvider in the ModelProvider). If this FIXME remains, then a separate issue should be opened to track it.

**Comment by Horsmann** [comment] 2015-12-15 13:29
I fixed the unused model-encoding parameters issue. I would open a new issue for starting/stopping the binary as you suggested.

**Comment by reckart** [comment] 2015-12-15 14:01
Why do we need the "de-tiger2treebank-pos.map" anyway? Tiger is using STTS and we already have the  "de-stts-pos.map". If we can use that (and I think we can) the build.xml and model files should be updated as using the STTS tagset.

**Comment by Horsmann** [comment] 2015-12-15 14:03
It is not identical to STTS. It is similar.

VFIN=de.tudarmstadt.ukp.dkpro.core.api.lexmorph.type.pos.V (tiger2tree)
VVFIN=de.tudarmstadt.ukp.dkpro.core.api.lexmorph.type.pos.V (STTS)

There are quite a few of this one-letter differences. I don't know why the RfTagger's mapping has this differences but they exist for other tags, too.

**Comment by reckart** [comment] 2015-12-15 14:06
Hum, strange. Can you please add a link to the documentation of the tagset used by RfTagger to the mapping file? We have such links in most mapping files. Also, please add an explanation to the file, e.g. "Variant of the STTS tagset used by the German model of RfTagger" or something like that. Feel free to be more verbose.

**Comment by Horsmann** [comment] 2015-12-15 14:15
I assume that the fine-grained morphological information that is outputted together with the basic tag are the reason for the slightly different tagging. What is usually expressed as own tag in STTS is now moved into the morphological information? 

This is the only reference I found that directly links the RfTagger's tags directly to the STTS. 
https://www.sketchengine.co.uk/xdocumentation/wiki/tagsets/german_rftagger

**Comment by reckart** [comment] 2015-12-15 14:47
Any link is better than none ;)

**Comment by reckart** [comment] 2015-12-15 16:31
Would you mind addressing the comments in the unit test as well? We have great support for testing in DKPro Core, asserts for all kinds of annotations and much more. This is already used in many test cases. Having uniform and terse tests across the codebase is a good thing.

**Comment by Horsmann** [comment] 2015-12-15 19:58
Oh sorry. I didn't look into the tests xD. I fix that tomorrow.

**Comment by Horsmann** [comment] 2015-12-16 08:00
I updated the tests with the suggested APIs

**Comment by reckart** [comment] 2015-12-17 23:10
@Horsmann I don't understand why you had to use `install-stub-and-upstream-folder` in the build file and work with folders. It is correct that the rftagger package contains additional files for the different languages, in particular abbreviation lists - however, you don't ever use them. They are used by the Perl-based tokenizer from rftagger which we do not use at all. The same for the multi-word lists.

So as far as I see, we only need to package the PAR files and then we can use `install-stub-and-upstream-file` and also use the hashes.

**Comment by Horsmann** [comment] 2015-12-18 07:04
I tried the previous version of the script before your update.
If I do not copy the other to files I got `FileNotFoundExceptions`.
So I assumed the parameter file is using them. I don't know why the exception does not occur in your version, but yes, if it works with a single file you can use the `-file` command

**Comment by reckart** [comment] 2015-12-18 23:48
Ok, this one has gotten the big makeover now. Puh!

For future work, let's open separate issues.

**Closed by reckart** 2015-12-18 23:48 UTC
Labels: enhancement, Module-rftagger
